"""Added genre and tags to writing_project

Revision ID: 01801e095973
Revises: 4cadc2f7c1f0
Create Date: 2023-10-16 22:06:32.456378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01801e095973'
down_revision = '4cadc2f7c1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_project_tags',
    sa.Column('writing_project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['writing_project_id'], ['writing_project.id'], ),
    sa.PrimaryKeyConstraint('writing_project_id', 'tag_id')
    )
    with op.batch_alter_table('writing_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'genre', ['genre_id'], ['id'])
        batch_op.create_foreign_key(None, 'project_template', ['project_template_id'], ['id'])
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writing_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('genre_id')
        batch_op.drop_column('project_template_id')

    op.drop_table('writing_project_tags')
    # ### end Alembic commands ###
