"""Updated HelpContext metadata

Revision ID: 2215eeb69449
Revises: b41e0dd12ada
Create Date: 2023-10-19 11:17:09.542871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2215eeb69449'
down_revision = 'b41e0dd12ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_context', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('modified', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_context', schema=None) as batch_op:
        batch_op.drop_column('modified')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
