"""Added category field to project_template

Revision ID: 4cadc2f7c1f0
Revises: 8fea4f57e428
Create Date: 2023-10-16 21:00:24.863511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cadc2f7c1f0'
down_revision = '8fea4f57e428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
