"""initial migration

Revision ID: 659ad5610d40
Revises: 
Create Date: 2023-10-14 17:30:27.091141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659ad5610d40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_project_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_project_title'), ['title'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chat_history_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_history_id'], ['chat_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    with op.batch_alter_table('writing_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_project_title'))
        batch_op.drop_index(batch_op.f('ix_writing_project_timestamp'))

    op.drop_table('writing_project')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
