"""setup

Revision ID: 7f7a478781fb
Revises: 
Create Date: 2023-10-21 09:55:24.891703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7a478781fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('help_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_context_context_id'), ['context_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_context_context_id'))

    op.drop_table('help_context')
    # ### end Alembic commands ###
