"""Implemented core models

Revision ID: aaf23a3614b7
Revises: d3bd5e51645c
Create Date: 2023-10-15 20:48:01.397119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaf23a3614b7'
down_revision = 'd3bd5e51645c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_created'), ['created'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('notification_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_last_modified'), ['last_modified'], unique=False)

    op.create_table('collaborators',
    sa.Column('writing_project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['writing_project_id'], ['writing_project.id'], ),
    sa.PrimaryKeyConstraint('writing_project_id', 'user_id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writing_project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['writing_project_id'], ['writing_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_last_modified'), ['last_modified'], unique=False)

    op.create_table('reviewers',
    sa.Column('writing_project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['writing_project_id'], ['writing_project.id'], ),
    sa.PrimaryKeyConstraint('writing_project_id', 'user_id')
    )
    op.create_table('story_part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writing_project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['story_part.id'], ),
    sa.ForeignKeyConstraint(['writing_project_id'], ['writing_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_part_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_part_last_modified'), ['last_modified'], unique=False)

    op.create_table('storypart_collection_link',
    sa.Column('story_part_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['story_part_id'], ['story_part.id'], ),
    sa.PrimaryKeyConstraint('story_part_id', 'collection_id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writing_project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_history_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_last_modified'), ['last_modified'], unique=False)
        batch_op.create_foreign_key(None, 'writing_project', ['writing_project_id'], ['id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Enum('all', 'collaborators', name='visibility_types'), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('user', 'assistant', 'system', name='role_types'),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('writing_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('visibility', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('project_type', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_writing_project_timestamp')
        batch_op.create_index(batch_op.f('ix_writing_project_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_project_last_modified'), ['last_modified'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writing_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_writing_project_last_modified'))
        batch_op.drop_index(batch_op.f('ix_writing_project_created'))
        batch_op.create_index('ix_writing_project_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')
        batch_op.drop_column('tags')
        batch_op.drop_column('project_type')
        batch_op.drop_column('visibility')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.Enum('user', 'assistant', 'system', name='role_types'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('visibility')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_history_last_modified'))
        batch_op.drop_index(batch_op.f('ix_chat_history_created'))
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')
        batch_op.drop_column('writing_project_id')

    op.drop_table('storypart_collection_link')
    with op.batch_alter_table('story_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_part_last_modified'))
        batch_op.drop_index(batch_op.f('ix_story_part_created'))

    op.drop_table('story_part')
    op.drop_table('reviewers')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_last_modified'))
        batch_op.drop_index(batch_op.f('ix_collection_created'))

    op.drop_table('collection')
    op.drop_table('collaborators')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_last_modified'))
        batch_op.drop_index(batch_op.f('ix_notification_created'))

    op.drop_table('notification')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_created'))

    op.drop_table('activity')
    # ### end Alembic commands ###
