"""Added help context

Revision ID: b41e0dd12ada
Revises: b3236e12d3d3
Create Date: 2023-10-19 09:12:53.850716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41e0dd12ada'
down_revision = 'b3236e12d3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('help_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_context_context_id'), ['context_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_context_context_id'))

    op.drop_table('help_context')
    # ### end Alembic commands ###
